export const cons = {
  UPDATE_SEARCH_TEXT: 'SEARCH:UPDATE_SEARCH_TEXT',
  RESET_SEARCH_TEXT: 'SEARCH:RESET_SEARCH_TEXT',

  UPDATE_FORM_FIELDS: 'FORM:UPDATE_FORM_FIELDS',
  RESET_FORM_FIELDS: 'FORM:RESET_FORM_FIELDS',

  CREATE_USER: 'FORM:CREATE_USER',
  FILL_FOR_EDIT: 'FORM:FILL_FOR_EDIT'
}
